name: Redeploy Streamlit ao mudar data/

on:
  push:
    paths:
      - "data/**"   # só dispara quando algo em data/ muda

permissions:
  contents: write

jobs:
  force-redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Config git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # Criamos/atualizamos um arquivo fora de data/ para evitar loop
      - name: Bump file p/ forçar redeploy
        run: |
          mkdir -p .streamlit
          date -u +"%Y-%m-%dT%H:%M:%SZ" > .streamlit/.force-redeploy
          git add .streamlit/.force-redeploy
          git commit -m "chore(redeploy): data/ mudou, forçando rebuild do Streamlit"

      - name: Push
        run: |
          git push
