# .github/workflows/sync_drive_to_data.yml
name: Sync Drive -> streamlit_app/data

on:
  schedule:
    - cron: "*/20 * * * *"  # a cada 20 min (agendamento é UTC)
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: America/Sao_Paulo  # fuso para logs e timestamps

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install google-api-python-client google-auth google-auth-httplib2

      - name: Restaurar credenciais do SA (base64)
        env:
          GDRIVE_SA_B64: ${{ secrets.GDRIVE_SA_B64 }}
        run: |
          printf "%s" "$GDRIVE_SA_B64" | base64 -d > sa.json
          python -c "import json; json.load(open('sa.json')); print('Credenciais OK')"

      - name: Baixar arquivo do Drive
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python streamlit_app/download_from_drive_folder.py \
            --folder-id "$GDRIVE_FOLDER_ID" \
            --target-name "OFERTASMATRIZ_OFERTAS.parquet" \
            --creds sa.json \
            --out-dir "streamlit_app/data" \
            --rename "OFERTASMATRIZ_OFERTAS.parquet"

      - name: Commit & push se houver mudanças
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "sync: update OFERTASMATRIZ_OFERTAS.parquet from Drive"
          file_pattern: "streamlit_app/data/OFERTASMATRIZ_OFERTAS.parquet"
